import SwiftUI
struct GameRootView:View{@StateObject private var game=CrownStore()
 var body:some View{ZStack{LinearGradient(colors:[Color(red:0.05,green:0.18,blue:0.34),Color(red:0.10,green:0.43,blue:0.49)],startPoint:.top,endPoint:.bottom).ignoresSafeArea();switch game.state{case .map:MapView().environmentObject(game);case .playing,.won,.lost:PlayView().environmentObject(game)}}.preferredColorScheme(.dark).alert("Daily Treasure!",isPresented:$game.showDaily){Button("Collect"){} }message:{Text("100 coins were added to your treasury.")}}}
struct MapView:View{@EnvironmentObject var game:CrownStore
 var body:some View{ScrollView{VStack(spacing:18){VStack(spacing:4){Image(systemName:"crown.fill").font(.system(size:58)).foregroundStyle(.yellow);Text("CROWN GARDENS").font(.system(size:34,weight:.black,design:.rounded));Text("Restore the enchanted royal gardens").foregroundStyle(.white.opacity(.75))}.padding(.top,22);HStack{StatPill(icon:"heart.fill",value:"\(game.save.lives)",color:.pink);StatPill(icon:"star.fill",value:"\(game.save.stars)",color:.yellow);StatPill(icon:"circle.fill",value:"\(game.save.coins)",color:.orange)}
 LazyVStack(spacing:12){ForEach(1...30,id:\.self){n in let open=n<=game.save.unlockedLevel;Button{if open && game.save.lives>0{game.start(n)}}label:{HStack(spacing:16){ZStack{Circle().fill(open ? Color.yellow.gradient:Color.gray.gradient).frame(width:58,height:58);Text("\(n)").font(.title2.bold()).foregroundStyle(open ? .black:.white.opacity(.5))};VStack(alignment:.leading,spacing:5){Text(Level.make(n).title).font(.headline);HStack(spacing:3){ForEach(0..<(game.save.completed[n] ?? 0),id:\.self){_ in Image(systemName:"star.fill").foregroundStyle(.yellow).font(.caption)}}};Spacer();Image(systemName:open ? "play.fill":"lock.fill")}.padding().background(.ultraThinMaterial,in:RoundedRectangle(cornerRadius:22))}.buttonStyle(.plain).disabled(!open)}}
 if game.save.lives==0{Button("Refill Lives • 250 Coins"){game.buyLives()}.buttonStyle(.borderedProminent).tint(.pink)}}.padding()}}}
struct StatPill:View{let icon:String,value:String,color:Color;var body:some View{Label(value,systemImage:icon).font(.headline.monospacedDigit()).foregroundStyle(color).padding(.horizontal,14).padding(.vertical,9).background(.black.opacity(.28),in:Capsule())}}
struct PlayView:View{@EnvironmentObject var game:CrownStore
 var body:some View{GeometryReader{geo in VStack(spacing:10){HStack{Button{game.map()}{Image(systemName:"chevron.left").font(.title2.bold())};Spacer();Text("LEVEL \(game.level.id)").font(.headline.bold());Spacer();Text("\(game.movesLeft)").font(.title2.bold().monospacedDigit()).frame(width:44).padding(7).background(.black.opacity(.3),in:Circle())}.padding(.horizontal);targets;BoardView().environmentObject(game).frame(width:min(geo.size.width-16,500),height:min(geo.size.width-16,500));HStack(spacing:30){VStack{Image(systemName:"hammer.fill").font(.title2);Text("Hold a tile").font(.caption2);Text("×\(game.save.hammer)").bold()};Button{game.shuffle()}label:{VStack{Image(systemName:"shuffle").font(.title2);Text("Shuffle").font(.caption2);Text("×\(game.save.shuffle)").bold()}}.buttonStyle(.plain)}.padding(.top,4);Text(game.message).font(.caption.bold()).foregroundStyle(.yellow).frame(height:18);Spacer()}.padding(.top,6)}.overlay{if game.state == .won{ResultCard(win:true).environmentObject(game)}else if game.state == .lost{ResultCard(win:false).environmentObject(game)}}}
 var targets:some View{HStack(spacing:8){ForEach(Array(game.remaining.keys),id:\.self){k in HStack(spacing:5){Image(systemName:k.symbol).foregroundStyle(k.color);Text("\(game.remaining[k] ?? 0)").bold().monospacedDigit()}.padding(.horizontal,10).padding(.vertical,7).background(.black.opacity(.25),in:Capsule())};Spacer();Text("\(game.score)").font(.caption.bold().monospacedDigit())}.padding(.horizontal)}}
struct BoardView:View{@EnvironmentObject var game:CrownStore
 var body:some View{GeometryReader{g in let s=g.size.width/8;ZStack{RoundedRectangle(cornerRadius:22).fill(.black.opacity(.24));VStack(spacing:2){ForEach(0..<8,id:\.self){r in HStack(spacing:2){ForEach(0..<8,id:\.self){c in let p=Cell(row:r,col:c);let t=game.board[r][c];GemView(tile:t,selected:game.selected==p).frame(width:s-2,height:s-2).contentShape(Rectangle()).onTapGesture{game.tap(p)}.gesture(DragGesture(minimumDistance:15).onEnded{v in game.swipe(from:p,dx:v.translation.width,dy:v.translation.height)}).contextMenu{Button("Hammer"){game.hammer(p)}}}}}.padding(3)}}}}
struct GemView:View{let tile:Tile;let selected:Bool
 var body:some View{ZStack{RoundedRectangle(cornerRadius:12).fill(tile.kind.color.gradient).shadow(color:tile.kind.color.opacity(.45),radius:selected ? 10:3).overlay(RoundedRectangle(cornerRadius:12).stroke(.white.opacity(selected ? 1:.25),lineWidth:selected ? 3:1));Image(systemName:tile.special == .bomb ? "burst.fill":tile.special == .rainbow ? "rainbow":tile.special == .rowRocket ? "arrow.left.and.right":tile.special == .columnRocket ? "arrow.up.and.down":tile.kind.symbol).font(.system(size:21,weight:.black)).foregroundStyle(.white).shadow(radius:2);if tile.blocker>0{RoundedRectangle(cornerRadius:12).stroke(.white.opacity(.85),lineWidth:4);Image(systemName:"snowflake").foregroundStyle(.white.opacity(.9))}}.scaleEffect(selected ? 1.08:1).animation(.spring(response:.2),value:selected)}}
struct ResultCard:View{@EnvironmentObject var game:CrownStore;let win:Bool
 var body:some View{ZStack{Color.black.opacity(.6).ignoresSafeArea();VStack(spacing:18){Image(systemName:win ? "crown.fill":"heart.slash.fill").font(.system(size:64)).foregroundStyle(win ? .yellow:.pink);Text(win ? "SPECTACULAR!":"SO CLOSE!").font(.largeTitle.black());Text(win ? "The garden shines brighter.":"Try a new strategy and come back stronger.").multilineTextAlignment(.center).foregroundStyle(.secondary);if win{HStack{ForEach(0..<(game.save.completed[game.level.id] ?? 1),id:\.self){_ in Image(systemName:"star.fill").font(.title).foregroundStyle(.yellow)}}};Button(win ? "NEXT LEVEL":"TRY AGAIN"){win ? game.next():game.start(game.level.id)}.buttonStyle(.borderedProminent).controlSize(.large).tint(win ? .green:.pink);Button("MAP"){game.map()}.buttonStyle(.bordered)}.padding(28).frame(maxWidth:340).background(.regularMaterial,in:RoundedRectangle(cornerRadius:30))}}}
